apiVersion: v1
kind: Service
metadata:
  name: streamlit-loadbalancer-service
  labels:
    app: streamlit
spec:
  type: LoadBalancer
  selector:
    app: streamlit
  ports:
    - port: 80
      targetPort: 80
